[project]
name = "ohw25_proj_BluRaspberry"
version = "0.1.0"
description = "Add a short description here"
authors = ["Christian P. Sarason <cbps@uw.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
copernicusmarine = ">=2.2.1,<3"
jupyter = ">=1.1.1,<2"
